### ISSUE TITLE
Infrastructure | Create Github Team

### ISSUE THREAD

**Issue by ghbjklhv** [Prometheus-SCN/js-offs#14]
**Feature**: Create Github Team
**Why?**: The first and foremost reason is that I think many users are interested in an OFF System reboot but yours can be hard to find. Hopefully, this may make it easier.

The second thing is preparing for other projects, like possibly writing clients in other languages
or, perhaps the documentation (#3 ) could have its own repository. :)

Best of luck!

**Comment by vijayee** [comment]
Certainly @ghbjklhv, I'll create a github team this weekend. The documentation site exists.  at https://www.off.system/. I'm already working on making a library to be extended by other languages https://github.com/vijayee/liboffs

**Comment by vijayee** [comment]
https://github.com/orgs/Prometheus-SCN/teams/offs
